dist: bionic
language: php
php:
- '5.6'
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: make docker-build
deploy:
  provider: script
  script: make docker-push
  on:
    branch: master
