language: php
php:
- '5.6'
services:
- docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script: make docker-build
deploy:
  provider: script
  script: make docker-push
  on:
    branch: master
env:
  global:
  - secure: Mk1i1pki+XB66be5+W9pp6eQctUEZBZ7cnZJa7CJPyAbxhy1UOa7ltOdeCsdRRlENFIPg0ixwI/NHFpRD2TddaqM/B4kMCSSG20R3EIIenpDQjTwf/su0UdkL20lHrraALkPX/iNa7EZ9XnfGYxNRdOg7PsqLwfBQiV5KjEGguXOh2jmOodiRUGSjPIi/BqgaA0vgkf/f/xv6o2AIFHLx+gwEnbyfBGxGXeF37iWhzhDee6s5ky407jK/ziAcvyccfvQpjk51ysYlUmz0FfW5/ExDXGelFWylzgGid6VgDVLAOsS2mk/E6X0vt0zNxsyLTi2CfAfTNRNj73+lIV+j62YS1cdQQ98H/FiKaI6xAXxuwI7FzCPXXs5jQsYtvig5v9Vsca1/PemIeD9/K795UphswujBe2yQeIezLBbhnbf6/3pMcfJTDH3j1i9b7YiFoPZqSs2smmGf0yfOlO7gldd0WcdeLWn75KO/Xi44UMyPdDY7oWxtKe2YCPHn6LgFdEKBLrNEKf+FvpsVmzhjEZsbxe1f9fSqJDfNqfiYdWwukOiARfFmnWioC0r+BhZdXKqUZvklSptwrc+HRJ5nOIDL9WA0M5TL0iVMbJwRqk8GGxF8guEyujPyo4sLa6OeFot/wgvWpKL17dKf704SWX4fjrjbLmorMsHiM+JtT8=
  - secure: t21jXcGyaCzNzP91+S0jXtoctGzB0WKAlvClwYwcUdx5JLBfJmymv7caXEsb5d6pfc46DRFXgNlQPwu8qUngkQ/YFn329DVAquKbvw5zyxQdWnNVt3VqISg/28e0KhKYtlfKl3Xy4Nza2xw1ua0BXo0L70z364Zbs8u7vD4gln57lC4K/5qTcr4CIktUHP0DoiBOZU3cSKRzfWUkKRdOtwZQadg1WXPZfzBtBlq40Edm24jsP0+Ksqo5H7spCkmwGEmixcU9UH0qmK79c68rej+b7Xlsse8KN+OoUTOqjnNCbjW2R8HE2F2bN0cZ03RN2dfsnMxzmFoUriVcnaG4rPvdaE8Yei+Gff9h/KjVmQ8ErGQ9r2Qcck+hApuSQ2Dq1mC23sRdvHOUp5hbKXUpqLLM7YsieNstK1Pvib02f+wvP2zAqiHO+IRrDZpwTyzqhXyPamb/XoSFDrxz07+Yu9DzB9uVOFyo/Pfe0js1cDUadkWvWYYLNz7Dbwz83ckM3eWJGAHy+idv2Nvl3mdsYSyVGiawT6qTnbamrXXVAXI09xxGKRBGRdoNI7lVKk0jz1uL2CAmt+fmHEGPcOBGQXMPX557my5ma3W5+lTfpuy/SV/saeFb6T9U6hY7LumKFCM5LxERKz88XiPcfOxp2gW+X9NeGYNmyjoJ3hJPyjI=
notifications:
  slack:
    secure: Nyy4JTz5SSpYnV0ombPvxH58GxFzQUM/sIXT1vymSyNO987vbfKGbtpr3C7wuhPh+2e4Gsof7fC5PfuzdbkZJub7uCHCtDu8SaZLMTHKEX0pUSNA8KFPFgpa05oorMfEIaLa6SByGaaQHkZYpcD88qGy486JUWYHqFNMe3g5qYg9puy2f9MUSFWVUsKI1CKdGTn4WXYUSQT7Jc4ObiRDl3NRglsW4Iw+4RuNYXD7Q6rpXRVd6/NAEo5dGgLkIRnRrQj4UgwdjM+ZRNdGJG4wciSdrLFoDF43kGqZpOukefqPQH0esRf5uEe4IYaSJQGKV3q3O2p2f0OOFUfm803Sx136HrY4ANqmeva09cWjSeXPWPLB+0+VS/V4rH0qyoRWAXMYc75cVP1lJoT171ZcaeJuTNiWvBPxQY2nqC6ip/a4CC/xLsyYx2xBSutIcqXfYkhMlXivA/wLJGwTw5vKeSlXxfXVsYRr5w9pZkF3X9yMxWgbxICQ2NtB2R1SRmYuUXUjshfuQILWNsTtZXEmLR6kcrzUzdGoPgOEHATgkhn8NNYYWdgDAdKruxZjwdiO8J1lOCbrmpdHtgk4L+MdIbE/2qBZV7R2YJZt5CUDLdiuerYOAgTxu9k4TumdbX43U/grUmo3WwlKMY9N+WOgDxtv//HuVCy1jd923Bt0s4E=
